---
abstract: 'introspect overloaded operators'
author:
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
build_requires:
  Test::Fatal: '0'
  Test::More: '0.88'
  parent: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Text::ParseWords: '0'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-OverloadInfo
requires:
  B: '0'
  Exporter: '5.57'
  MRO::Compat: '0'
  Package::Stash: '0.14'
  Scalar::Util: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Devel-OverloadInfo
  repository: git://github.com/ilmari/Devel-OverloadInfo
version: '0.007'
x_generated_by_perl: v5.33.9
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
